### PR TITLE
New chapter

### PR DESCRIPTION
**Pull request by tomyuval**

### CODE REVIEW

**Comment by tomyuval** [comment]
Hey @sharkdp, I've added a new chapter (Chapter 4, keeping the previous Chapter 4 last, now as Chapter 5). Check it out!

Reservations:
- I'm new to PureScript, so it's possible my code is not the most idiomatic.
- I'm new to this repository, so it's possible some of my changes and/or additions are not perfectly in line with the existing style and/or intent.
- I haven't invested too much time into it; while I think the new levels I've added are nice and my difficulty indications are roughly suitable, it's possible they could be made nicer and/or someone else will find them easier.

So I'm open to feedback, and otherwise feel free to merge the new levels in whole or in part, as is or with further changes.

**Comment by sharkdp** [comment]
Thank you very much! I like it!

Is it possible to create harder levels with this idea? I basically solved all of the existing levels on first try (loved the idea of the last level, where `partition*` is not needed).

**Comment by tomyuval** [comment]
Thanks for the feedback, @sharkdp!

> (loved the idea of the last level, where `partition*` is not needed)

Yeah, I thought it would be a nice twist :)
But you don't mean the _last_ level, but rather the _third_ level (out of five), right? That's the one that does not make use of `partition*`, while the last one actually does.

> Is it possible to create harder levels with this idea?

I thought the _last_ level (the one which is really last) was a bit challenging – have you tried it and found it too easy?

In any case, it's certainly possible to make harder levels too! I pushed some ideas – all variations on the original last level – to https://github.com/tomyuval/cube-composer/tree/706cc9132397ecf835ff406f4bf3b8b4a4518213, check it out (all levels of Chapter 4 there – they replace the current levels; it's not meant to be merged as is, just to give us some ideas to play around with).

I might also try other levels based on slightly different themes with the same transformers.

**Comment by sharkdp** [comment]
Oh, I think I only played the first three levels for some reason :smile:. Will have another look when I find the time.

**Comment by tomyuval** [comment]
Great, @sharkdp!

In the meantime I've added yet more potential levels at https://github.com/tomyuval/cube-composer/tree/6ef76cc20c7f5fa17cad4535cbe02f4666fadadf.

**Comment by sharkdp** [comment]
I played the other levels now. I love it. Should I merge it in this state or do you want to experiment with other levels first?

**Comment by tomyuval** [comment]
Awesome, @sharkdp, happy to hear it!
I'm happy with merging the current PR as is; we (you, I, anyone else) can always suggest improvements at a later stage :)

**Comment by sharkdp** [comment]
Deployed :-)

Thanks!

**Pull request merged**
