### PR TITLE
Pin versions

### PR DESCRIPTION
**Pull request by tomyuval**
This enables building the project locally once again (#44).

### CODE REVIEW

**Comment by tomyuval** [comment]
(Note: I've force-pushed a superficial update, changing commit meta-information; the content of the commits remains the same.)

**Comment by sharkdp** [comment]
Thank you! I'm afraid we need this 15k lines lock file?

**Comment by tomyuval** [comment]
> Thank you!

It's a pleasure!

> I'm afraid we need this 15k lines lock file?

Interesting point! It's standard practice (see for example [this answer on StackOverflow](https://stackoverflow.com/a/44210813)), and it serves, among other things, to ensure each developer working on the code base uses the exact same versions of all packages. Also, the file is about half a meg, which is not _that_ big (well, it _is_ big relative to the size of what's committed to source control – but quite negligible relative to the size of the local repository when all npm packages are installed!), plus it's not meant to significantly change often.

That said, it's the first commit (7d3e16d1e026d0ebd87223c9e937f3dadf63d972) which got the project to build successfully, so if you're unhappy about the commit which introduces `package-lock.json` (93b644710660eeecade2681e9c926aed22023d57) feel free to only pull the former! (I guess that there's a chance that something else might go wrong in the future where having the version locks could help, but that that chance is rather small, and we can always deal with that when it happens – if ever. But again, it seems to me the cost of preventing it isn't that big either in this case... So really, it's your call 🙂)

**Comment by sharkdp** [comment]
Ok, thank you for the explanation. Seems like a good idea. Especially since the code, tooling and dependencies are all out of date.

**Pull request merged**
